apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-frontend
spec:
  selector:
    matchLabels:
      app: portal-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: portal-frontend
    spec:
      containers:
        - name: portal-frontend
          image: ahmadaboualshamat/portal-frontend
          imagePullPolicy: IfNotPresent
#          restartPolicy: always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portal-frontend-service
spec:
  selector:
    app: portal-frontend
  ports:
    - protocol: "TCP"
      port: 3000 # port of service inside the cluster
      targetPort: 3000 # port exposed by this service
  type: NodePort # type of service